USERS = [
    {
        'name': 'John Smith',
        'email': 'jsmith@gmail.com',
        'age': 20
    },
    {
        'name': 'Bari Pushard',
        'email': 'bpushard@gmail.com',
        'age': 21
    },
    {
        'name': 'Irish Rackers',
        'email': 'irackers@gmail.com',
        'age': 22
    },
    {
        'name': 'Agueda Letsinger',
        'email': 'aletsinger@gmail.com',
        'age': 23
    },
    {
        'name': 'Lisbeth Stacker',
        'email': 'lstacker@gmail.com',
        'age': 24
    },
    {
        'name': 'John Smith',
        'email': 'jsmith@gmail.com',
        'age': 20
    },
    {'name': 'user1', 'email': 'email1@gmail.com', 'age': 1},
{'name': 'user2', 'email': 'email2@gmail.com', 'age': 2},
{'name': 'user3', 'email': 'email3@gmail.com', 'age': 3},
{'name': 'user4', 'email': 'email4@gmail.com', 'age': 4},
{'name': 'user5', 'email': 'email5@gmail.com', 'age': 5},
{'name': 'user6', 'email': 'email6@gmail.com', 'age': 6},
{'name': 'user7', 'email': 'email7@gmail.com', 'age': 7},
{'name': 'user8', 'email': 'email8@gmail.com', 'age': 8},
{'name': 'user9', 'email': 'email9@gmail.com', 'age': 9},
{'name': 'user10', 'email': 'email10@gmail.com', 'age': 10},
{'name': 'user11', 'email': 'email11@gmail.com', 'age': 11},
{'name': 'user12', 'email': 'email12@gmail.com', 'age': 12},
{'name': 'user13', 'email': 'email13@gmail.com', 'age': 13},
{'name': 'user14', 'email': 'email14@gmail.com', 'age': 14},
{'name': 'user15', 'email': 'email15@gmail.com', 'age': 15},
{'name': 'user16', 'email': 'email16@gmail.com', 'age': 16},
{'name': 'user17', 'email': 'email17@gmail.com', 'age': 17},
{'name': 'user18', 'email': 'email18@gmail.com', 'age': 18},
{'name': 'user19', 'email': 'email19@gmail.com', 'age': 19},
{'name': 'user20', 'email': 'email20@gmail.com', 'age': 20},
{'name': 'user21', 'email': 'email21@gmail.com', 'age': 21},
{'name': 'user22', 'email': 'email22@gmail.com', 'age': 22},
{'name': 'user23', 'email': 'email23@gmail.com', 'age': 23},
{'name': 'user24', 'email': 'email24@gmail.com', 'age': 24},
{'name': 'user25', 'email': 'email25@gmail.com', 'age': 25},
{'name': 'user26', 'email': 'email26@gmail.com', 'age': 26},
{'name': 'user27', 'email': 'email27@gmail.com', 'age': 27},
{'name': 'user28', 'email': 'email28@gmail.com', 'age': 28},
{'name': 'user29', 'email': 'email29@gmail.com', 'age': 29},
{'name': 'user30', 'email': 'email30@gmail.com', 'age': 30},
{'name': 'user31', 'email': 'email31@gmail.com', 'age': 31},
{'name': 'user32', 'email': 'email32@gmail.com', 'age': 32},
{'name': 'user33', 'email': 'email33@gmail.com', 'age': 33},
{'name': 'user34', 'email': 'email34@gmail.com', 'age': 34},
{'name': 'user35', 'email': 'email35@gmail.com', 'age': 35},
{'name': 'user36', 'email': 'email36@gmail.com', 'age': 36},
{'name': 'user37', 'email': 'email37@gmail.com', 'age': 37},
{'name': 'user38', 'email': 'email38@gmail.com', 'age': 38},
{'name': 'user39', 'email': 'email39@gmail.com', 'age': 39},
{'name': 'user40', 'email': 'email40@gmail.com', 'age': 40},
{'name': 'user41', 'email': 'email41@gmail.com', 'age': 41},
{'name': 'user42', 'email': 'email42@gmail.com', 'age': 42},
{'name': 'user43', 'email': 'email43@gmail.com', 'age': 43},
{'name': 'user44', 'email': 'email44@gmail.com', 'age': 44},
{'name': 'user45', 'email': 'email45@gmail.com', 'age': 45},
{'name': 'user46', 'email': 'email46@gmail.com', 'age': 46},
{'name': 'user47', 'email': 'email47@gmail.com', 'age': 47},
{'name': 'user48', 'email': 'email48@gmail.com', 'age': 48},
{'name': 'user49', 'email': 'email49@gmail.com', 'age': 49}
]